### ISSUE TITLE
UI for trashing containers and boxes

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-element-trash-drupal#1]
Please tell me about the hook @mkernel than I'll build the module

**Comment by mkernel** [comment]
there exists 3 hooks in drupal you need to be aware of:
- hook_grid_boxes_search_alter($array,$grid_id,$node_id)
- hook_grid_containers_alter($array,$grid_id,$node_id)
- hook_grid_reusable_containers_alter($array,$grid_id,$node_id)

in all three functions $array contains the dataset to "modify". The easiest way is to use array_splice:

```
for($i=0;i$,count($array);$i++)
{
    if($array[$i]['type']=='deleted_type')
    {
        array_splice($array,$i,1);
        $i--;
    }
}
```

the structure of $array differs between the three calls and they can be looked up in the json calls "Search", "getContainerTypes" and "getReusableContainers".

**Comment by EdwardBock** [comment]
Important & :

```
hook_grid_boxes_search_alter(&$array,$grid_id,$node_id)
hook_grid_containers_alter(&$array,$grid_id,$node_id)
hook_grid_reusable_containers_alter(&$array,$grid_id,$node_id)
```

**Comment by EdwardBock** [comment]
@mkernel 
Box and Container types are trashable. Next step #2
