### ISSUE TITLE
Reusable Containers and Boxes

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-element-trash-drupal#3]
Reusable Elements should be trashable too

**Comment by EdwardBock** [comment]
@mkernel 
I think we need a box reuse title for the trash. Otherwise it is nearly impossible to identify the boxes.

**Comment by EdwardBock** [comment]
https://github.com/palasthotel/grid/issues/362

**Comment by mkernel** [comment]
@EdwardBock that's only partly true: you could easliy load and render the box-as is. The Problem is this: a title itself will not really help as humans are visual people. They'll misuse the name. So I would say: render the box for selecting which one should go into the trash.

**Comment by EdwardBock** [comment]
is working
